import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./LoadingCircle.css";
import GlobalState from "@/context";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense> */}
        <GlobalState>
          <Navbar />

          <main className="flex min-h-screen flex-col mt-[80px]">
            {children}
          </main>
        </GlobalState>
        {/* </Suspense> */}
      </body>
    </html>
  );
}
